//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMRON_IFZ_Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMRON_IFZ_Viewer.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch convert.
        /// </summary>
        internal static string CM_BatchConvert {
            get {
                return ResourceManager.GetString("CM_BatchConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CM_Copy {
            get {
                return ResourceManager.GetString("CM_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path.
        /// </summary>
        internal static string CM_CopyPath {
            get {
                return ResourceManager.GetString("CM_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CM_Erase {
            get {
                return ResourceManager.GetString("CM_Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in file explorer.
        /// </summary>
        internal static string CM_OpenFolder {
            get {
                return ResourceManager.GetString("CM_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string CM_Openwith {
            get {
                return ResourceManager.GetString("CM_Openwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string CM_Print {
            get {
                return ResourceManager.GetString("CM_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string CM_Saveas {
            get {
                return ResourceManager.GetString("CM_Saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Confirm_cancel {
            get {
                return ResourceManager.GetString("Confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Confirm_delete {
            get {
                return ResourceManager.GetString("Confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        internal static string Confirm_label1 {
            get {
                return ResourceManager.GetString("Confirm_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this file?.
        /// </summary>
        internal static string Confirm_label2 {
            get {
                return ResourceManager.GetString("Confirm_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Convert_cancel {
            get {
                return ResourceManager.GetString("Convert_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert_convert {
            get {
                return ResourceManager.GetString("Convert_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose file format and options before pressing Convert..
        /// </summary>
        internal static string Convert_label {
            get {
                return ResourceManager.GetString("Convert_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch ifz conversion.
        /// </summary>
        internal static string Convert_title {
            get {
                return ResourceManager.GetString("Convert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows scale factor is {0}%, zoom should be set to 100% so that zooming functions works correctly!.
        /// </summary>
        internal static string DPI_Message {
            get {
                return ResourceManager.GetString("DPI_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for IFZ.
        /// </summary>
        internal static string EmptyFolder_browse {
            get {
                return ResourceManager.GetString("EmptyFolder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel &amp; Close.
        /// </summary>
        internal static string EmptyFolder_cancel {
            get {
                return ResourceManager.GetString("EmptyFolder_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder is empty!.
        /// </summary>
        internal static string EmptyFolder_label1 {
            get {
                return ResourceManager.GetString("EmptyFolder_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not contains any IFZ images. Please select a folder that contains IFZ..
        /// </summary>
        internal static string EmptyFolder_label2 {
            get {
                return ResourceManager.GetString("EmptyFolder_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info.
        /// </summary>
        internal static string lblCamera {
            get {
                return ResourceManager.GetString("lblCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Value:.
        /// </summary>
        internal static string lblColor {
            get {
                return ResourceManager.GetString("lblColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string lblFolder {
            get {
                return ResourceManager.GetString("lblFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Value:.
        /// </summary>
        internal static string lblMono {
            get {
                return ResourceManager.GetString("lblMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Info.
        /// </summary>
        internal static string lblSize {
            get {
                return ResourceManager.GetString("lblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Settings_btnClose {
            get {
                return ResourceManager.GetString("Settings_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Settings_btnInstall {
            get {
                return ResourceManager.GetString("Settings_btnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to fit window.
        /// </summary>
        internal static string Settings_cb2_opt1 {
            get {
                return ResourceManager.GetString("Settings_cb2_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to real image scale.
        /// </summary>
        internal static string Settings_cb2_opt2 {
            get {
                return ResourceManager.GetString("Settings_cb2_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Settings_lbl1 {
            get {
                return ResourceManager.GetString("Settings_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_lbl2 {
            get {
                return ResourceManager.GetString("Settings_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_lbl3 {
            get {
                return ResourceManager.GetString("Settings_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFZ Viewer.
        /// </summary>
        internal static string Settings_lbl4 {
            get {
                return ResourceManager.GetString("Settings_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom preference.
        /// </summary>
        internal static string Settings_lbl5 {
            get {
                return ResourceManager.GetString("Settings_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Background Color.
        /// </summary>
        internal static string Settings_lbl6 {
            get {
                return ResourceManager.GetString("Settings_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install windows shell extension to create IFZ thumbnails in the explorer..
        /// </summary>
        internal static string Settings_lbl7 {
            get {
                return ResourceManager.GetString("Settings_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        internal static string tooltip_delete {
            get {
                return ResourceManager.GetString("tooltip_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip image horizontally.
        /// </summary>
        internal static string tooltip_flip_h {
            get {
                return ResourceManager.GetString("tooltip_flip_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip image vertically.
        /// </summary>
        internal static string tooltip_flip_v {
            get {
                return ResourceManager.GetString("tooltip_flip_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen (F11).
        /// </summary>
        internal static string tooltip_fullscreen {
            get {
                return ResourceManager.GetString("tooltip_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (I, Ctrl+I).
        /// </summary>
        internal static string tooltip_info {
            get {
                return ResourceManager.GetString("tooltip_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder (Ctrl+O).
        /// </summary>
        internal static string tooltip_open_folder {
            get {
                return ResourceManager.GetString("tooltip_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print (Ctrl+P).
        /// </summary>
        internal static string tooltip_print {
            get {
                return ResourceManager.GetString("tooltip_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ribbon (F, Ctrl+F).
        /// </summary>
        internal static string tooltip_ribbon {
            get {
                return ResourceManager.GetString("tooltip_ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate (R, Ctrl+R).
        /// </summary>
        internal static string tooltip_rotate {
            get {
                return ResourceManager.GetString("tooltip_rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tooltip_settings {
            get {
                return ResourceManager.GetString("tooltip_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to fit screen (Ctrl+0).
        /// </summary>
        internal static string tooltip_zoom_fit {
            get {
                return ResourceManager.GetString("tooltip_zoom_fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in (Ctrl +).
        /// </summary>
        internal static string tooltip_zoom_in {
            get {
                return ResourceManager.GetString("tooltip_zoom_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out (Ctrl -).
        /// </summary>
        internal static string tooltip_zoom_out {
            get {
                return ResourceManager.GetString("tooltip_zoom_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to real size (Ctrl+1).
        /// </summary>
        internal static string tooltip_zoom_realsize {
            get {
                return ResourceManager.GetString("tooltip_zoom_realsize", resourceCulture);
            }
        }
    }
}
