//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMRON_IFZ_Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMRON_IFZ_Viewer.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string CM_Copy {
            get {
                return ResourceManager.GetString("CM_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as path.
        /// </summary>
        internal static string CM_CopyPath {
            get {
                return ResourceManager.GetString("CM_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string CM_Erase {
            get {
                return ResourceManager.GetString("CM_Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in file explorer.
        /// </summary>
        internal static string CM_OpenFolder {
            get {
                return ResourceManager.GetString("CM_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open with.
        /// </summary>
        internal static string CM_Openwith {
            get {
                return ResourceManager.GetString("CM_Openwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        internal static string CM_Print {
            get {
                return ResourceManager.GetString("CM_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as.
        /// </summary>
        internal static string CM_Saveas {
            get {
                return ResourceManager.GetString("CM_Saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Confirm_cancel {
            get {
                return ResourceManager.GetString("Confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Confirm_delete {
            get {
                return ResourceManager.GetString("Confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this file?.
        /// </summary>
        internal static string Confirm_label1 {
            get {
                return ResourceManager.GetString("Confirm_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this file?.
        /// </summary>
        internal static string Confirm_label2 {
            get {
                return ResourceManager.GetString("Confirm_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Convert_cancel {
            get {
                return ResourceManager.GetString("Convert_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert.
        /// </summary>
        internal static string Convert_convert {
            get {
                return ResourceManager.GetString("Convert_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose file format and options before pressing Convert..
        /// </summary>
        internal static string Convert_label {
            get {
                return ResourceManager.GetString("Convert_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Batch ifz conversion.
        /// </summary>
        internal static string Convert_title {
            get {
                return ResourceManager.GetString("Convert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows scale factor is {0}%, zoom should be set to 100% so that zooming functions works correctly!.
        /// </summary>
        internal static string DPI_Message {
            get {
                return ResourceManager.GetString("DPI_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse for IFZ.
        /// </summary>
        internal static string EmptyFolder_browse {
            get {
                return ResourceManager.GetString("EmptyFolder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel &amp; Close.
        /// </summary>
        internal static string EmptyFolder_cancel {
            get {
                return ResourceManager.GetString("EmptyFolder_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder is empty!.
        /// </summary>
        internal static string EmptyFolder_label1 {
            get {
                return ResourceManager.GetString("EmptyFolder_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This folder does not contains any IFZ images. Please select a folder that contains IFZ..
        /// </summary>
        internal static string EmptyFolder_label2 {
            get {
                return ResourceManager.GetString("EmptyFolder_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device Info.
        /// </summary>
        internal static string lblCamera {
            get {
                return ResourceManager.GetString("lblCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RGB Value:.
        /// </summary>
        internal static string lblColor {
            get {
                return ResourceManager.GetString("lblColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Path.
        /// </summary>
        internal static string lblFolder {
            get {
                return ResourceManager.GetString("lblFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pixel Value:.
        /// </summary>
        internal static string lblMono {
            get {
                return ResourceManager.GetString("lblMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size Info.
        /// </summary>
        internal static string lblSize {
            get {
                return ResourceManager.GetString("lblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Settings_btnClose {
            get {
                return ResourceManager.GetString("Settings_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        internal static string Settings_btnInstall {
            get {
                return ResourceManager.GetString("Settings_btnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to fit window.
        /// </summary>
        internal static string Settings_cb2_opt1 {
            get {
                return ResourceManager.GetString("Settings_cb2_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to real image scale.
        /// </summary>
        internal static string Settings_cb2_opt2 {
            get {
                return ResourceManager.GetString("Settings_cb2_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize.
        /// </summary>
        internal static string Settings_lbl1 {
            get {
                return ResourceManager.GetString("Settings_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Settings_lbl2 {
            get {
                return ResourceManager.GetString("Settings_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string Settings_lbl3 {
            get {
                return ResourceManager.GetString("Settings_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IFZ Viewer.
        /// </summary>
        internal static string Settings_lbl4 {
            get {
                return ResourceManager.GetString("Settings_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom preference.
        /// </summary>
        internal static string Settings_lbl5 {
            get {
                return ResourceManager.GetString("Settings_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows integration.
        /// </summary>
        internal static string Settings_lbl6 {
            get {
                return ResourceManager.GetString("Settings_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install windows shell extension to create IFZ thumbnails in the explorer..
        /// </summary>
        internal static string Settings_lbl7 {
            get {
                return ResourceManager.GetString("Settings_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Screen (F11).
        /// </summary>
        internal static string tooltip_001 {
            get {
                return ResourceManager.GetString("tooltip_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to real size (Ctrl+1).
        /// </summary>
        internal static string tooltip_002 {
            get {
                return ResourceManager.GetString("tooltip_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to fit screen (Ctrl+0).
        /// </summary>
        internal static string tooltip_003 {
            get {
                return ResourceManager.GetString("tooltip_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate (Ctrl+R).
        /// </summary>
        internal static string tooltip_004 {
            get {
                return ResourceManager.GetString("tooltip_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete (Del).
        /// </summary>
        internal static string tooltip_005 {
            get {
                return ResourceManager.GetString("tooltip_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        internal static string tooltip_006 {
            get {
                return ResourceManager.GetString("tooltip_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string tooltip_007 {
            get {
                return ResourceManager.GetString("tooltip_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip image horizontally.
        /// </summary>
        internal static string tooltip_008 {
            get {
                return ResourceManager.GetString("tooltip_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip image vertically.
        /// </summary>
        internal static string tooltip_009 {
            get {
                return ResourceManager.GetString("tooltip_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom in (Ctrl +).
        /// </summary>
        internal static string tooltip_010 {
            get {
                return ResourceManager.GetString("tooltip_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom out (Ctrl -).
        /// </summary>
        internal static string tooltip_011 {
            get {
                return ResourceManager.GetString("tooltip_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Ribbon (F).
        /// </summary>
        internal static string tooltip_012 {
            get {
                return ResourceManager.GetString("tooltip_012", resourceCulture);
            }
        }
    }
}
